require('dotenv').config();
const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require('fs');
const path = require('path');

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generateBlog() {
    if (!process.env.GEMINI_API_KEY) {
        console.error("Error: GEMINI_API_KEY is not set in .env.local");
        process.exit(1);
    }

    try {
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `
            You are a technical content creator for "TechSheet", an educational platform for developers.
            Generate a high-quality technical blog post (cheatsheet style) about a random trending web development topic (e.g., React hooks, SQL optimization, Docker basics, CSS Container Queries, etc.).
            
            Return the response in a VALID JSON format with the following structure:
            {
              "title": "A catchy title",
              "tags": "TAG1 TAG2 TAG3",
              "abstract": "A short 1-2 sentence summary",
              "imageKeyword": "a single keyword for a relevant background image",
              "sections": [
                {
                  "heading": "Section Heading",
                  "id": "URL-friendly-id",
                  "content": "Detailed content in Markdown format including code blocks if applicable"
                }
              ]
            }
            
            IMPORTANT: Use the {#id} syntax for headings in the markdown content if you write subheaders manually, but for the "sections" array, provide the id separately.
            Ensure the content is accurate, educational, and professional.
        `;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        let text = response.text();

        // Clean the response (sometimes Gemini returns markdown code blocks around JSON)
        text = text.replace(/```json/g, '').replace(/```/g, '').trim();

        const topic = JSON.parse(text);
        const id = Math.floor(1000 + Math.random() * 9000);
        const fileName = `BL-${id}.md`;
        const filePath = path.join(process.cwd(), '_content', fileName);

        const date = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        });

        const markdown = `---
Id: ${id}
Title: ${topic.title}
Author: TechSheet AI
Tags: ${topic.tags}
Abstract: ${topic.abstract}
HeaderImage: https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1000&auto=format&fit=crop&q=80&keywords=${encodeURIComponent(topic.imageKeyword || 'coding')}
isPublished: true
GeneratedAt: ${new Date().toISOString()}
---

`;

        topic.sections.forEach(section => {
            markdown += `## ${section.heading} {#${section.id}}\n\n`;
            markdown += `${section.content}\n\n`;
        });

        markdown += `*This post was automatically generated by Gemini AI for educational purposes on ${date}.*`;

        fs.writeFileSync(filePath, markdown);
        console.log(`Successfully generated new AI blog: ${fileName} - ${topic.title}`);
    } catch (error) {
        console.error("Error generating blog:", error);
    }
}

generateBlog();
